export const ActionTypes = {
  ADD_TODO: "ADD_TODO",
  DELETE_TODO: "DELETE_TODO",
  UPDATE_TODO: "UPDATE_TODO",
  COMPLETE_TODO: "COMPLETE_TODO",
  REQUIRED_TODO: "REQUIRED_TODO",
  CHECK_ALL: "CHECK_ALL",
};
